routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\hasta;
use App\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::group(['prefix' => 'admin'], function() {
    Auth::routes(['register' => false]);
});

Route::group(['middleware'=>'auth'],function (){
    Route::get('/', function () {
        $subecount =\App\Sube::all()->count();
        $hocacount =\App\Hoca::all()->count();
        $hastacount =\App\hasta::all()->count();
        $dokumancount = \App\Dokuman::all()->count();
        $tutar =\App\Odeme::all();
        $para=0;
        foreach ($tutar as $t){
            $para +=$t->tutar;
        }
        $alinan =0;
        $alinanpara = \App\hasta::all();
        foreach ($alinanpara as $h){
           $alinan+= $h->alinan_ucret;
        }

        $connect_web = simplexml_load_file('http://www.tcmb.gov.tr/kurlar/today.xml');

        $usd_buying = $connect_web->Currency[0]->BanknoteBuying;
        $usd_selling = $connect_web->Currency[0]->BanknoteSelling;
        $euro_buying = $connect_web->Currency[3]->BanknoteBuying;
        $euro_selling = $connect_web->Currency[3]->BanknoteSelling;

        $kurlar =[
            'usd-alis' =>$usd_buying,
            'usd-satis'=>$usd_selling,
            'euro-alis' =>$euro_buying,
            'euro-satis' =>$euro_selling,
        ];

        $today = new Carbon('now');
        $tomorrow = new Carbon('now');
        $tomorrow = $tomorrow->add(1,'day');
       if(auth()->user()->role == 'SuperAdmin'){
           $hasta = hasta::where('arama','>=',$today)
               ->where('arama','<=',$tomorrow)
               ->orderBy('arama','asc')
               ->get();

       }else{
           $hasta = hasta::where('arama','>=',$today)
               ->where('arama','<=',$tomorrow)
               ->where('user_id',auth()->user()->id)
               ->orderBy('arama','asc')
               ->get();
       }

       //Anasayfa Aramalar listesi hastaları döndürecek
        $hastalar = hasta::where('user_id',\auth()->user()->id)->orderBy('arama','asc')->paginate(10);

        return view('backend.home.index')->with('hocacount',$hocacount)->with('hastacount',$hastacount)
            ->with('subecount',$subecount)->with('odeme',$para)->with('alinan',$alinan)->with('kurlar',$kurlar)
            ->with('dokumancount',$dokumancount)->with('hasta',$hasta)->with('hastalar',$hastalar);
    });

    Route::get('/hastalar','HastaController@index')->name('hastalar.tumhastalar');
    Route::get('/hastalar/yhasta','HastaController@create')->name('hastalar.yenihasta');
    Route::post('/hastalar/ekle','HastaController@store')->name('hastalar.ekle');
    Route::delete('/hastalar/{id}','HastaController@destroy')->name('hastalar.sil');
    Route::get('/hastalar/{id}/duzenle','HastaController@edit')->name('hastalar.edit');
    Route::put('/hastalar/{id}','HastaController@update')->name('hastalar.update');
    Route::post('/hastalar/dinamik','HastaController@DynamicSelect')->name('hastalar.dinamik');
    Route::get('/hastalar/datatable','HastaController@datatable')->name('hastalar.datatable');
    Route::get('/hastalar/arama-kontrol','HastaController@arama_kontrol')->name('hastalar.arama-kontrol');
    Route::post('/hasta/{id}/arandi','HastaController@arandi')->name('hastalar.arandi');

    Route::get('hastalar/odeme/{id}/sil','HastaController@odemesil')->name('hastalar.odemesil');
    Route::post('hastalar/odeme/ekle','HastaController@odemeekle')->name('hastalar.odemeekle');

    Route::resource('bakimlar','BakimController')->except('destroy');
    Route::get('bakimlar/datatable/get','BakimController@datatable')->name('bakimlar.datatable');
    Route::get('bakimlar/{id}/destroy','BakimController@destroy2')->name('bakimlar.destroy2');

    Route::get('bakilmlar/bakilan/bakim','BakimController@bakilanlar')->name('bakim.bakılanlar');
    Route::get('bakimlar/datatable/get/bakilanlar','BakimController@bakilandatatable')->name('bakimlar.bakilanlar.datatable');

    Route::get('bakilmlar/bakilmayan/bakim','BakimController@bakilanlar')->name('bakim.bakılmayanlar');
    Route::get('bakimlar/datatable/get/bakilmayanlar','BakimController@bakilandatatable')->name('bakimlar.bakilmayanlar.datatable');

    Route::get('bakilmlar/tedavikabul/bakim','BakimController@tedavikabul')->name('bakim.tedavikabul');
    Route::get('bakimlar/datatable/get/tedavikabul','BakimController@tedavikabuldatatable')->name('bakimlar.tedavikabul.datatable');

    Route::get('bakilmlar/tedavired/bakim','BakimController@tedavired')->name('bakim.tedavired');
    Route::get('bakimlar/datatable/get/tedavired','BakimController@tedavireddatatable')->name('bakimlar.tedavired.datatable');

    Route::get('/muhasebe','HastaController@muhasebee')->name('muhasebe.index')->middleware('isAdmin');
    Route::get('muhasebe/datatable/get','HastaController@mdatatable')->name('muhasebe.datatable')->middleware('isAdmin');

    Route::resource('/subeler','SubelerController');
    Route::get('subeler/datatable/get','SubelerController@datatable')->name('subeler.datatable');

    Route::get('subeler/{id}/hocalar','SubelerController@hocaindex')->name('subeler.hocaindex');
    Route::get('subeler/{id}/hocaekle','SubelerController@hocacreate')->name('subeler.hocacreate');
    Route::post('subeler/{id}/hocaekle','SubelerController@hocastore')->name('subeler.hocastore');
    Route::put('subeler/{id}/hocaekle','SubelerController@hocaupdate')->name('subeler.hocaupdate');
    Route::get('subeler/{id}/hoca/edit','SubelerController@hocaedit')->name('subeler.hocaedit');
    Route::get('subeler/hocadestroy/{id}','SubelerController@hocadestroy')->name('subeler.hocadelete');
    Route::get('subeler/{id}/datatable/get','SubelerController@hdatatable')->name('subeler.hdatatable');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/ayarlar/durum','DurumController');
    Route::get('/ayarlar/durum/datatable/get','DurumController@datatable')->name('durum.datatable');

    Route::resource('/ayarlar/grup','GrupController');
    Route::get('/ayarlar/grup/datatable/get','GrupController@datatable')->name('grup.datatable');


    Route::get('/kullanici/{id}/delete','KullaniciController@destroy')->name('kullanici.destroy')->middleware('isAdmin');
    Route::get('/kullanici/{id}/superadmin','KullaniciController@superadmin')->name('kullanici.destroy')->middleware('isAdmin');

    Route::resource('ayarlar/okuma','OkumaController');
    Route::get('/ayarlar/okuma/datatable/get','OkumaController@datatable')->name('okuma.datatable');
    Route::post('hastalar/{id}/okuma','HastaController@hastaokuma')->name('okuma.hastaekle');
    Route::delete('hastalar/{id}/okuma','HastaController@hastaokumasil')->name('okuma.hastasil');

    Route::resource('ayarlar/temizlik','TemizlikController');
    Route::get('/ayarlar/temizlik/datatable/get','TemizlikController@datatable')->name('temizlik.datatable');
    Route::post('hastalar/{id}/temizlik','HastaController@hastatemizlik')->name('temizlik.hastaekle');
    Route::delete('hastalar/{id}/temizlik','HastaController@hastatemizliksil')->name('temizlik.hastasil');

    Route::resource('ayarlar/dokuman','DokumanController');
    Route::get('/ayarlar/dokuman/datatable/get','DokumanController@datatable')->name('dokuman.datatable');
    Route::post('hastalar/{id}/dokuman','HastaController@hastadokuman')->name('dokuman.hastaekle');
    Route::delete('hastalar/{id}/dokuman','HastaController@hastadokumansil')->name('dokuman.hastasil');
    Route::post('hasta/dokuman/{id}','DokumanController@download')->name('dokuman.download');

    Route::post('hastalar/{id}/not','NotController@store')->name('not.ekle');
    Route::delete('hastalar/{id}/not','NotController@destroy')->name('not.sil');
    Route::get("/hasta/not/{id}", "NotController@index")->name('not.goster');

});

Route::resource('kullanici','KullaniciController')->except('destroy');
Route::get('/kullanici/datatable/get','KullaniciController@datatable')->name('kullanici.datatable');

app/Okuma.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Okuma extends Model
{
    protected $fillable =['adi'];

    public function hastas(){
        return $this->belongsToMany(hasta::class)->withPivot('tarih')->withTimestamps();
    }
}

app/Http/Controllers/OkumaController.php
<?php

namespace App\Http\Controllers;

use App\Durum;
use App\Okuma;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class OkumaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.Ayarlar.Okuma.okumalar');
    }

    public function datatable()
    {
        $data = Okuma::latest()->get();
        return Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('action', function($row){
                $btn ='<div class="d-flex" >
                   <a href="#" class="edit btn btn-outline-light text-warning btn-sm" id="modal-delete" data-action-target="/ayarlar/okuma/'.$row->id.'" onclick="onay(this);" "><i class="fa fa-trash"></i></a>
                   <a href="/ayarlar/okuma/'.$row->id.'/edit" class="edit btn btn-outline-light text-success btn-sm" ><i class="fa fa-edit"></i></a>
                </div>';
                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.Ayarlar.Okuma.createOkuma');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $data = $request->only('adi');
       if (Okuma::create($data)){
           session()->flash('success','Okuma eklendi');
           return redirect(route('okuma.index'));
       }
        session()->flash('error','Okuma eklenemedi, bilgileri kontoller ediniz.');
        return redirect(route('okuma.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Okuma  $okuma
     * @return \Illuminate\Http\Response
     */


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Okuma  $okuma
     * @return \Illuminate\Http\Response
     */
    public function edit(Okuma $okuma)
    {
        return view('backend.Ayarlar.Okuma.createOkuma')->with('okuma',$okuma);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Okuma  $okuma
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Okuma $okuma)
    {
        $data= $request->only('adi');
        $okuma->update($data);
        if ($okuma->save()){
            session()->flash('success','Okuma güncellendi');
            return redirect(route('okuma.index'));
        }
        session()->flash('error','Okuma güncellenemedi, bilgileri kontoller ediniz.');
         return redirect(route('okuma.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Okuma  $okuma
     * @return \Illuminate\Http\Response
     */
    public function destroy(Okuma $okuma)
    {
        if ($okuma->delete()){
            session()->flash('success','Okuma silindi.');
            return redirect(route('okuma.index'));
        }
        session()->flash('error','Okuma silinemedi, bilgileri kontoller ediniz.');
        return redirect(route('okuma.index'));
    }
}

resources/views/backend/Ayarlar/Okuma/createOkuma.blade.php
@extends('layouts.main')
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>@isset($okuma) Okumayı Düzenle @else Okuma Ekle @endisset</h2>
            </div>
            @include('layouts._alerts')
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>  Okuma Bilgileri </h2>
                        </div>
                        <form action="@isset($okuma) {{route('okuma.update',$okuma->id)}} @else {{(route('okuma.store'))}} @endisset " method="post">
                            @csrf
                            @isset($okuma)
                                @method('PUT')
                            @endisset
                            <div class="form-group row">
                                <div class="col-sm-2">
                                    <label for="adi"> Adı: *</label>
                                </div>
                                <div class="col-sm-10">
                                    <div class="form-line">
                                        <input type="text" value="@isset($okuma){{$okuma->adi}}@endisset" class="form-control " name="adi" id="adi" placeholder=" Adı:" minlength="2" required>
                                    </div>
                                </div>

                            </div>

                            <div class="form-group">
                                <div class="col-sm-12 text-center">
                                    <button type="submit" class="btn btn-raised g-bg-cyan btn-lg" > Ekle</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('css')

    <link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/button.css')}}">
@endsection
@section('js')
    <script src="{{asset('assets/js/bootstrap.min.js')}}"></script>

@endsection

resources/views/backend/Ayarlar/Okuma/okumalar.blade.php
@extends('layouts.main')
@section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <section class="content">
        <div class="container-fluid">
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="header">
                            <h2>Tüm Okuma Ayarları</h2>
                            <ul class="header-dropdown">
                                <a href="{{route('okuma.create')}}" class="yesilbutton btn-round">Yeni Okuma Ekle</a>
                            </ul>
                        </div>
                        <div class="body table-responsive mt-2">
                            <table class="table table-bordered table-striped table-hover js-basic-example dataTable" id="okumalar-table" style="width: 100%">
                                <thead>
                                <tr>
                                    <th style="width: 5%;">ID</th>
                                    <th style="width: 15%;">Ad</th>
                                    <th style="width: 10%;">İşlemler</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
@endsection
@section('js')
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{asset('assets/js/pages/ui/modals.js')}}"></script>
    <script src="{{asset('assets/bundles/datatablescripts.bundle.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script>
        $(document).ready(function () {
            $('#okumalar-table').DataTable({
                language:{"url":"//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"},
                processing: true,
                serverSide: true,
                ajax: '{!! route('okuma.datatable') !!}',
                columns: [
                    { data: 'id', name: 'id'},
                    { data: 'adi', name: 'adi' },
                    { data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        })
    </script>
    <script>
        function onay(obj) {
            var target= obj.getAttribute('data-action-target') ;
            console.log(target);
            Swal.fire({
                title: 'Emin misiniz?',
                text: "Bu şubeyi silmek istediğinize emin misiniz? ",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'İptal',
                confirmButtonText: 'Sil'
            }) .then((result)=>{
                    if(result.value){
                        $.ajax({
                            type: "DELETE",
                            url: target,
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            contentType: false,
                            processData: false,
                            success: function (data) {
                                console.log(data);
                                Swal.fire({
                                        title: 'Başarılı',
                                        text: 'Okuma silindi',
                                        icon: 'success'
                                    }
                                ).then(()=>
                                    window.location.reload()
                                );

                            }
                            //silme işlemi başka sayfada olacaksa dosya adı gir
                        });
                    }
                }
            )
        }
    </script>
@endsection
@section('css')
    <link href="{{asset('assets/css/button.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">

@endsection