routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\hasta;
use App\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::group(['prefix' => 'admin'], function() {
    Auth::routes(['register' => false]);
});

Route::group(['middleware'=>'auth'],function (){
    Route::get('/', function () {
        $subecount =\App\Sube::all()->count();
        $hocacount =\App\Hoca::all()->count();
        $hastacount =\App\hasta::all()->count();
        $dokumancount = \App\Dokuman::all()->count();
        $tutar =\App\Odeme::all();
        $para=0;
        foreach ($tutar as $t){
            $para +=$t->tutar;
        }
        $alinan =0;
        $alinanpara = \App\hasta::all();
        foreach ($alinanpara as $h){
           $alinan+= $h->alinan_ucret;
        }

        $connect_web = simplexml_load_file('http://www.tcmb.gov.tr/kurlar/today.xml');

        $usd_buying = $connect_web->Currency[0]->BanknoteBuying;
        $usd_selling = $connect_web->Currency[0]->BanknoteSelling;
        $euro_buying = $connect_web->Currency[3]->BanknoteBuying;
        $euro_selling = $connect_web->Currency[3]->BanknoteSelling;

        $kurlar =[
            'usd-alis' =>$usd_buying,
            'usd-satis'=>$usd_selling,
            'euro-alis' =>$euro_buying,
            'euro-satis' =>$euro_selling,
        ];

        $today = new Carbon('now');
        $tomorrow = new Carbon('now');
        $tomorrow = $tomorrow->add(1,'day');
       if(auth()->user()->role == 'SuperAdmin'){
           $hasta = hasta::where('arama','>=',$today)
               ->where('arama','<=',$tomorrow)
               ->orderBy('arama','asc')
               ->get();

       }else{
           $hasta = hasta::where('arama','>=',$today)
               ->where('arama','<=',$tomorrow)
               ->where('user_id',auth()->user()->id)
               ->orderBy('arama','asc')
               ->get();
       }

       //Anasayfa Aramalar listesi hastaları döndürecek
        $hastalar = hasta::where('user_id',\auth()->user()->id)->orderBy('arama','asc')->paginate(10);

        return view('backend.home.index')->with('hocacount',$hocacount)->with('hastacount',$hastacount)
            ->with('subecount',$subecount)->with('odeme',$para)->with('alinan',$alinan)->with('kurlar',$kurlar)
            ->with('dokumancount',$dokumancount)->with('hasta',$hasta)->with('hastalar',$hastalar);
    });

    Route::get('/hastalar','HastaController@index')->name('hastalar.tumhastalar');
    Route::get('/hastalar/yhasta','HastaController@create')->name('hastalar.yenihasta');
    Route::post('/hastalar/ekle','HastaController@store')->name('hastalar.ekle');
    Route::delete('/hastalar/{id}','HastaController@destroy')->name('hastalar.sil');
    Route::get('/hastalar/{id}/duzenle','HastaController@edit')->name('hastalar.edit');
    Route::put('/hastalar/{id}','HastaController@update')->name('hastalar.update');
    Route::post('/hastalar/dinamik','HastaController@DynamicSelect')->name('hastalar.dinamik');
    Route::get('/hastalar/datatable','HastaController@datatable')->name('hastalar.datatable');
    Route::get('/hastalar/arama-kontrol','HastaController@arama_kontrol')->name('hastalar.arama-kontrol');
    Route::post('/hasta/{id}/arandi','HastaController@arandi')->name('hastalar.arandi');

    Route::get('hastalar/odeme/{id}/sil','HastaController@odemesil')->name('hastalar.odemesil');
    Route::post('hastalar/odeme/ekle','HastaController@odemeekle')->name('hastalar.odemeekle');

    Route::resource('bakimlar','BakimController')->except('destroy');
    Route::get('bakimlar/datatable/get','BakimController@datatable')->name('bakimlar.datatable');
    Route::get('bakimlar/{id}/destroy','BakimController@destroy2')->name('bakimlar.destroy2');

    Route::get('bakilmlar/bakilan/bakim','BakimController@bakilanlar')->name('bakim.bakılanlar');
    Route::get('bakimlar/datatable/get/bakilanlar','BakimController@bakilandatatable')->name('bakimlar.bakilanlar.datatable');

    Route::get('bakilmlar/bakilmayan/bakim','BakimController@bakilanlar')->name('bakim.bakılmayanlar');
    Route::get('bakimlar/datatable/get/bakilmayanlar','BakimController@bakilandatatable')->name('bakimlar.bakilmayanlar.datatable');

    Route::get('bakilmlar/tedavikabul/bakim','BakimController@tedavikabul')->name('bakim.tedavikabul');
    Route::get('bakimlar/datatable/get/tedavikabul','BakimController@tedavikabuldatatable')->name('bakimlar.tedavikabul.datatable');

    Route::get('bakilmlar/tedavired/bakim','BakimController@tedavired')->name('bakim.tedavired');
    Route::get('bakimlar/datatable/get/tedavired','BakimController@tedavireddatatable')->name('bakimlar.tedavired.datatable');

    Route::get('/muhasebe','HastaController@muhasebee')->name('muhasebe.index')->middleware('isAdmin');
    Route::get('muhasebe/datatable/get','HastaController@mdatatable')->name('muhasebe.datatable')->middleware('isAdmin');

    Route::resource('/subeler','SubelerController');
    Route::get('subeler/datatable/get','SubelerController@datatable')->name('subeler.datatable');

    Route::get('subeler/{id}/hocalar','SubelerController@hocaindex')->name('subeler.hocaindex');
    Route::get('subeler/{id}/hocaekle','SubelerController@hocacreate')->name('subeler.hocacreate');
    Route::post('subeler/{id}/hocaekle','SubelerController@hocastore')->name('subeler.hocastore');
    Route::put('subeler/{id}/hocaekle','SubelerController@hocaupdate')->name('subeler.hocaupdate');
    Route::get('subeler/{id}/hoca/edit','SubelerController@hocaedit')->name('subeler.hocaedit');
    Route::get('subeler/hocadestroy/{id}','SubelerController@hocadestroy')->name('subeler.hocadelete');
    Route::get('subeler/{id}/datatable/get','SubelerController@hdatatable')->name('subeler.hdatatable');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/ayarlar/durum','DurumController');
    Route::get('/ayarlar/durum/datatable/get','DurumController@datatable')->name('durum.datatable');

    Route::resource('/ayarlar/grup','GrupController');
    Route::get('/ayarlar/grup/datatable/get','GrupController@datatable')->name('grup.datatable');


    Route::get('/kullanici/{id}/delete','KullaniciController@destroy')->name('kullanici.destroy')->middleware('isAdmin');
    Route::get('/kullanici/{id}/superadmin','KullaniciController@superadmin')->name('kullanici.destroy')->middleware('isAdmin');

    Route::resource('ayarlar/okuma','OkumaController');
    Route::get('/ayarlar/okuma/datatable/get','OkumaController@datatable')->name('okuma.datatable');
    Route::post('hastalar/{id}/okuma','HastaController@hastaokuma')->name('okuma.hastaekle');
    Route::delete('hastalar/{id}/okuma','HastaController@hastaokumasil')->name('okuma.hastasil');

    Route::resource('ayarlar/temizlik','TemizlikController');
    Route::get('/ayarlar/temizlik/datatable/get','TemizlikController@datatable')->name('temizlik.datatable');
    Route::post('hastalar/{id}/temizlik','HastaController@hastatemizlik')->name('temizlik.hastaekle');
    Route::delete('hastalar/{id}/temizlik','HastaController@hastatemizliksil')->name('temizlik.hastasil');

    Route::resource('ayarlar/dokuman','DokumanController');
    Route::get('/ayarlar/dokuman/datatable/get','DokumanController@datatable')->name('dokuman.datatable');
    Route::post('hastalar/{id}/dokuman','HastaController@hastadokuman')->name('dokuman.hastaekle');
    Route::delete('hastalar/{id}/dokuman','HastaController@hastadokumansil')->name('dokuman.hastasil');
    Route::post('hasta/dokuman/{id}','DokumanController@download')->name('dokuman.download');

    Route::post('hastalar/{id}/not','NotController@store')->name('not.ekle');
    Route::delete('hastalar/{id}/not','NotController@destroy')->name('not.sil');
    Route::get("/hasta/not/{id}", "NotController@index")->name('not.goster');

});

Route::resource('kullanici','KullaniciController')->except('destroy');
Route::get('/kullanici/datatable/get','KullaniciController@datatable')->name('kullanici.datatable');

resources/views/layouts/_alerts.blade.php
<div class="container">
    @if($errors->any())
        <div class="alert alert-danger" style="background-color: #ff9600 !important;">
            @foreach($errors->all() as $messages)
                <li style="list-style-type: none">{{$messages}}</li>
            @endforeach
        </div>
    @endif
    @if(session()->has('success'))
        <div class="alert alert-success" style="background-color: #00b0e4 !important;">
            <strong>Başarılı!  </strong>  {{session()->get('success')}}
        </div>
    @endif
    @if(session()->has('error'))
        <div class="alert alert-warning" style="background-color: #ff9600 !important;">
            <strong>Başarısız!  </strong>    {{session()->get('error')}}
        </div>
    @endif
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Kainat Enerjisi </title>
    <link rel="icon" href="{{asset('assets/images/Logoo/hatemhocalogo.png')}}" type="image/x-icon">
    <link href="{{asset('assets/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <link href="{{asset('assets/plugins/morrisjs/morris.css')}}" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="{{asset('assets/css/main.css')}}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <!-- Swift Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{asset('assets/css/themes/all-themes.css')}}" rel="stylesheet" />

    <style>
        .li a {
            font-family: 'Poppins', sans-serif; !important;
            font-size: 14px; !important;
            color: #2b2b2b;
        }
        li a:hover{
            color:#337ab7;
        }
        body {
            font-family: 'Poppins', sans-serif; !important;
            font-size: 14px; !important;
        }
    </style>
    @yield('css')
</head>

<body class="theme-cyan">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-cyan">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Yükleniyor</p>
    </div>
</div>
<!-- #END# Page Loader -->
<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->


<!-- Top Bar -->
<nav class="navbar clearHeader">
    <div class="col-12">

        <div class="logo" style=" position:fixed;   ">
            <a class="navbar-brand" style="font-size: 18px;color: white; font-weight: bold;display: inline;text-decoration: none;margin-left: -7px" href="/">
                <div class="navbar-header"> <a href="javascript:void(0);" class="bars"></a> </div>
                <a href="/"> <img style="margin-top: -10px;margin-left: -25px" width="40px" height="40px" class="hidden-lg-down" src="{{asset('assets/images/Logoo/hatemhocalogo.png')}}" alt="hatemhoca"></a>
                <h3 class="hidden-lg-down text-white" style="display: inline">Kainat Enerjisi</h3>
            </a>
        </div>
    </div>
</nav>
<!-- #Top Bar -->
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="admin-image"> <img  src="{{asset('assets/images/random-avatar7.jpg')}}" alt=""> </div>
            <div class="admin-action-info"> <span>Hoş Geldiniz</span>
                <h3>@if(auth()->user()) {{auth()->user()->name}} @endif</h3>
                <ul>
                    <li>
                       @auth()
                            <form id="logout-form" action="{{ route('logout') }}" method="POST">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-outline-primary text-white btn-sm fa fa-user" > Çıkış Yap</button>
                            </form>
                           @endauth
                        <br>
                    </li>
                </ul>
            </div>

        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">MENÜ</li>
                <li class="active open"><a href="/"><i class="zmdi zmdi-home"></i><span>Anasayfa</span></a></li>
                <li class=""><a href="/hastalar"><i class="fa fa-user "></i><span>Hastalar</span></a></li>
                <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-account-o"></i><span>Bakım</span> </a>
                    <ul class="ml-menu">
                        <li><a href="{{route('bakim.bakılanlar')}}">Bakılanlar</a></li>
                        <li><a href="{{route('bakim.bakılmayanlar')}}">Bakılmayanlar</a></li>
                        <li><a href="{{route('bakim.tedavikabul')}}">Tedavi Kabul Edenler</a></li>
                        <li><a href="{{route('bakim.tedavired')}}">Tedavi Kabul Etmeyenler</a></li>
                        <li><a href="{{route('bakimlar.index')}}">Tüm Bakımlar</a></li>
                    </ul>
                </li>
                <li><a href="{{route('bakimlar.index')}}" class=""><i class="fa fa-eye"></i><span>Bakım</span> </a>

                </li>
                <li><a href="{{route("subeler.index")}}"><i class="zmdi zmdi-file-text"></i><span>Şubeler</span></a></li>
                 <li><a href="{{route('muhasebe.index')}}"><i class="fa fa-calculator"></i><span>Muhasebe</span></a></li>
                <li> <a href="{{route("kullanici.index")}}" class=""><i class="fa fa-user-secret"></i><span>Kullanıcılar</span> </a></li>
                <li> <a href="javascript:void(0);" class="menu-toggle"><i class="fa fa-gear"></i><span>Ayarlar (UI)</span> </a>
                    <ul class="ml-menu">
                        <li> <a href="{{route('okuma.index')}}">Okuma Ayarları</a> </li>
                        <li> <a href="{{route('temizlik.index')}}">Temizlik Ayarları</a></li>
                        <li> <a href="{{route('durum.index')}}">Durum Ayarları</a> </li>
                        <li> <a href="{{route('grup.index')}}">Grup Ayarları</a> </li>
                        <li> <a href="{{route('dokuman.index')}}">Doküman Ayarları</a> </li>

                    </ul>
                </li>

            </ul>
        </div>
        <!-- #Menu -->
    </aside>
    <!-- #END# Left Sidebar -->
    <!-- Right Sidebar -->

    <!-- #END# Right Sidebar -->
</section>
{{--İçerik alanı Başlabgıç--}}

@yield('content')
{{--İçerik alanı sonu--}}
<div class="color-bg"></div>
<!-- Jquery Core Js -->
<script src="{{asset('assets/bundles/libscripts.bundle.js')}}"></script> <!-- Lib Scripts Plugin Js -->
<script src="{{asset('assets/bundles/morphingsearchscripts.bundle.js')}}"></script> <!-- morphing search Js -->
<script src="{{asset('assets/bundles/vendorscripts.bundle.js')}}"></script> <!-- Lib Scripts Plugin Js -->
<script src="{{asset('assets/bundles/morphingscripts.bundle.js')}}"></script><!-- morphing search page js -->

<script src="{{asset('assets/plugins/jquery-sparkline/jquery.sparkline.min.js')}}"></script> <!-- Sparkline Plugin Js -->
<script src="{{asset('assets/plugins/chartjs/Chart.bundle.min.js')}}"></script> <!-- Chart Plugins Js -->

<script src="{{asset('assets/bundles/mainscripts.bundle.js')}}"></script><!-- Custom Js -->

<script src="{{asset('assets/js/pages/charts/sparkline.min.js')}}"></script>

@yield('js')
</body>
</html>